export const faceAnimList = [
    { name: translateText("Normal"), animName: null },
    { name: translateText("Aiming"), animName: "mood_aiming_1" },
    { name: translateText("Mad"), animName: "mood_angry_1" },
    { name: translateText("Drunk"), animName: "mood_drunk_1" },
    { name: translateText("Happy"), animName: "mood_happy_1" },
    { name: translateText("The victim"), animName: "mood_injured_1" },
    { name: translateText("Anger"), animName: "mood_stressed_1" },
    { name: translateText("Offended"), animName: "mood_sulk_1" },
];

export const animationList = [
    { name: translateText("Fist to chest"), dict: "cellphone@self@franklin@", anim: "chest_bump" },
    { name: translateText("Peace"), dict: "cellphone@self@franklin@", anim: "peace" },
    { name: "West Coast", dict: "cellphone@self@franklin@", anim: "west_coast" },
    { name: translateText("Show on camera"), dict: "cellphone@self@michael@", anim: "finger_point" },
    { name: translateText("Fix your face"), dict: "cellphone@self@michael@", anim: "run_chin" },
    { name: translateText("Stretch your neck"), dict: "cellphone@self@michael@", anim: "stretch_neck" },
    { name: translateText("Aggressive fuck"), dict: "cellphone@self@trevor@", anim: "aggressive_finger" },
    { name: translateText("Proud fuck"), dict: "cellphone@self@trevor@", anim: "proud_finger" },
    { name: translateText("Cut the throat"), dict: "cellphone@self@trevor@", anim: "throat_slit" },
    { name: translateText("Air kiss"), dict: "anim@mp_player_intselfieblow_kiss" },
    { name: translateText("Ok"), dict: "anim@mp_player_intselfiedock" },
    { name: translateText("Nice"), dict: "anim@mp_player_intselfiejazz_hands" },
    { name: translateText("Fuck"), dict: "anim@mp_player_intselfiethe_bird" },
    { name: translateText("Thumb"), dict: "anim@mp_player_intselfiethumbs_up" },
    { name: translateText("Twitch your hand"), dict: "anim@mp_player_intselfiewank" },
];

export const timeCycle = [
    "",
    "NG_filmic01",
    "NG_filmic02",
    "NG_filmic03",
    "NG_filmic04",
    "NG_filmic05",
    "NG_filmic06",
    "NG_filmic07",
    "NG_filmic08",
    "NG_filmic09",
    "NG_filmic10",
    "NG_filmic11",
    "NG_filmic12",
    "NG_filmic13",
    "NG_filmic14",
    "NG_filmic15",
    "NG_filmic16",
    "NG_filmic17",
    "NG_filmic18",
    "NG_filmic19",
    "NG_filmic20",
    "NG_filmic21",
    "NG_filmic22",
    "NG_filmic23",
    "NG_filmic24",
    "NG_filmic25",
];

export const clampMin = (value, minClamp, maxClamp) => Math.min(maxClamp, Math.max(minClamp, value));
