export const accessKeyToId = {
    "Gov": 1,
    "TakeGuns": 2,
    "Warg": 3,
    "Ems": 4,
    "OpenWeaponStock": 5,
    "OpenStock": 6,
    "SetRank": 7,
    "Invite": 8,
    "UnInvite": 9,
    "Ticket": 10,
    "Arrest": 11,
    "Rfp": 12,
    "Follow": 13,
    "Su": 14,
    "InCar": 15,
    "Pull": 16,
    "TakeGunLic": 17,
    "TakeHelLic": 18,
    "TakePlaneLic": 19,
    "GiveGunLic": 20,
    "StealGuns": 21,
    "Pocket": 22,
    "GivePmLic": 23,
    "GiveMedLic": 24,
    "Medkit": 25,
    "Heal": 26,
    "Dep": 27,
    "TakeMats": 28,
    "TakeDrugs": 29,
    "TakeMoney": 30,
    "TakeMedkits": 31,
    "TakeStock": 32,
    "Capture": 33,
    "BuyDrugs": 34,
    "Delad": 35,
    "BizWar": 36,
    "Cuff": 37,
    "SetVehicleRank": 38,
    "DoorControl": 39,

    "TableWall": 40,
    "EditAllTabletWall": 41,
    "OrgTuning": 42,
    "OrgBuyCars": 43,
    "OrgSellCar": 44,
    "OrgUpgrate": 45,
    "OrgCrime": 46,

    "Logs": 47,
    "Reprimand": 48,
    "Dron": 49,
    "Ads": 50,

    "CaptureJoin": 51,
    "BizwarJoin": 52,

    "VehicleTicket": 53,

    "CreateDepartment": 54,
    "UpdateDepartment": 55,
    "DeleteDepartment": 56,
    "InviteDepartment": 57,

    "ClothesEdit": 58,

    "OpenGunStock": 59,

    "FamilyZone": 60,
    "IsWar": 61,
    "StartLiveStream": 62,
}

export const accessIdToKey = {
    1: 'Gov',
    2: 'TakeGuns',
    3: 'Warg',
    4: 'Ems',
    5: 'OpenWeaponStock',
    6: 'OpenStock',
    7: 'SetRank',
    8: 'Invite',
    9: 'UnInvite',
    10: 'Ticket',
    11: 'Arrest',
    12: 'Rfp',
    13: 'Follow',
    14: 'Su',
    15: 'InCar',
    16: 'Pull',
    17: 'TakeGunLic',
    18: 'TakeHelLic',
    19: 'TakePlaneLic',
    20: 'GiveGunLic',
    21: 'StealGuns',
    22: 'Pocket',
    23: 'GivePmLic',
    24: 'GiveMedLic',
    25: 'Medkit',
    26: 'Heal',
    27: 'Dep',
    28: 'TakeMats',
    29: 'TakeDrugs',
    30: 'TakeMoney',
    31: 'TakeMedkits',
    32: 'TakeStock',
    33: 'Capture',
    34: 'BuyDrugs',
    35: 'Delad',
    36: 'BizWar',
    37: 'Cuff',
    38: 'SetVehicleRank',
    39: 'DoorControl',
    40: 'TableWall',
    41: 'EditAllTabletWall',
    42: 'OrgTuning',
    43: 'OrgBuyCars',
    44: 'OrgSellCar',
    45: 'OrgUpgrate',
    46: 'OrgCrime',
    47: 'Logs',
    48: 'Reprimand',
    49: 'Dron',
    50: 'Ads',
    51: 'CaptureJoin',
    52: 'BizwarJoin',
    53: 'VehicleTicket',

    54: 'CreateDepartment',
    55: 'UpdateDepartment',
    56: 'DeleteDepartment',
    57: 'InviteDepartment',
    58: 'ClothesEdit',
    59: 'OpenGunStock',

    60: 'FamilyZone',
    61: 'IsWar',
    62: 'StartLiveStream',
}


export const accessKeyToName = {
    "Gov": "State Wave",
    "TakeGuns": "Confiscate",
    "Warg": "Emergency mode",
    "Ems": "Accept call",
    "OpenWeaponStock": "Open warehouse",
    "OpenStock": "Warehouse management",
    "SetRank": "Rank Settings",
    "Invite": "Invite Into Fraction",
    "UnInvite": "Fire From Fraction",
    "Ticket": "Write fine",
    "Arrest": "Arrest",
    "Rfp": "Rfp",
    "Follow": "Drag",
    "Su": "Wanted List",
    "InCar": "In Car",
    "Pull": "Pull",
    "TakeGunLic": "Take Gun License",
    "TakeHelLic": "Take Heli License",
    "TakePlaneLic": "Take Plane License",
    "GiveGunLic": "Give Gun License",
    "StealGuns": "Steal Guns",
    "Pocket": "Search pockets",
    "GivePmLic": "Give Paramedic License",
    "GiveMedLic": "Give Medic License",
    "Medkit": "Sell aidlit",
    "Heal": "Heal",
    "Dep": "Department",
    "TakeMats": "Take Materiald",
    "TakeDrugs": "Take Drugs",
    "TakeMoney": "Take money",
    "TakeMedkits": "Take aidkits",
    "TakeStock": "Take from warehouse",
    "Capture": "Capture",
    "BuyDrugs": "Buy Drugs",
    "Delad": "Deleting add",
    "BizWar": "Bizwar",
    "Cuff": "Cuff",
    "SetVehicleRank": "Set vehicle rank",
    "DoorControl": "Door Control",

    "TableWall": "Add post in tablet",
    "EditAllTabletWall": "Managing adds in tablet",
    "OrgTuning": "Transport Tune",
    "OrgBuyCars": "Buying Transport",
    "OrgSellCar": "Selling Transport",
    "OrgUpgrate": "Buying Upgrade",
    "OrgCrime": "Criminal actions",

    "Logs": "Accesd to logs",
    "Reprimand": "Reprimand",

    "Dron": "Drone",
    "Ads": "Ads",

    "CaptureJoin": "Capture Join",
    "BizwarJoin": "Bizwar Join",

    "VehicleTicket": "Vehicle Ticket",

    "CreateDepartment": "Create Department",
    "UpdateDepartment": "Update Department",
    "DeleteDepartment": "Delete Department",
    "InviteDepartment": "Invite Department",

    "ClothesEdit": "Clothes Edit",

    "OpenGunStock": "Gun Warehouse",

    "FamilyZone": "Family Zone",
    "IsWar": "Is War",
    "StartLiveStream":"Live",
}

export const accessType = {
    Add: 0,
    Remove: 1,
    Skip: 2
}