using System.Collections.Generic;
using NeptuneEvo.BattlePass.Models;
using NeptuneEvo.Chars.Models;

namespace NeptuneEvo.BattlePass.Season1Models
{
    public static class Repository
    {
               
        public static readonly List<BattlePassTask> BattlePassTask = new List<BattlePassTask>
        {
	        new BattlePassTask(0, "Take part in the Gun Game", 1, 30, "Let's go out", "Unusual task", 777, BattlePassRewardDiff.Medium),
			new BattlePassTask(1, "Buy a weapon modification at the Gun Shop", 1, 30, "Weapon Customization", "Easy Mission", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(2, "Drive 5 miles with a passenger as a taxi driver," 5.30, "Taxi Driver Junior," "Unusual Task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(3, "Play Minesweeper (F9)", 1, 30, "Bomb has been defused", "Unusual task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(4, "Play the Slots at the Casino," 1, 30, "Three Axes," "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(5, "Add $10 to your bank account using an ATM," 1, 30, "Money," "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(6, "Buy a Lottery Ticket 24/7", 1, 30, "Lucky?", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(7, "Resuscitate a person using a first aid kit", 1, 30, "I need a medic!", "A difficult task", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(8, "Buy any clothes at the Clothes Shop," 1, 30, "Fashion Sentence," "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(9, "Get an entry-level job (at City Hall)", 1, 30, "Work again...", "Easy task", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(10, "Quitting My Entry-Level Job (at City Hall)", 1, 30, "Day Off...", "Easy Task", 333, BattlePassRewardDiff.Easy),
			new BattlePassTask(11, "Submit 3 ads to NEWS via phone", 3, 30, "Everyone will hear me!", "Easy task.", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(12, "Fix the vehicle with a wrench," 1, 30, "Wrench," "Easy task.", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(13, "Fix the vehicle at the repair hub at the mechanics' spawn," 1, 30, "Fix my car!", "Unusual task", 250, BattlePassRewardDiff.Medium),
			new BattlePassTask(14, "Give money to someone", 1, 30, "Bring the money to Mom!", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(15, "Buy a pill from a doctor in EMS", 1, 30, "Doctor!!!", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(16, "Drop any object on the floor", 1, 30, "Bookmark", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(17, "Pick up any object from the floor", 1, 30, "Looted", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(18, "Get a tattoo on any part of the body", 1, 30, "Tattooist, tattoo me...", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(19, "Fill up 20 liters of fuel at the gas station," 1, 30, "Pour it into my tank," "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(20, "Deliver 10 parcels as a postman," 9:30, "You've got mail!", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(21, "Drive 20 Marks While Working as a Lawn Mower," 20, 30, "Illegal Racer," "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(22, Fix 20 electrical units as an electrician, 20, 30, Fixie, Unusual Task, 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(23, "Set Off Fireworks," 1, 30, "My Art Is an Explosion!", "An Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(24, "Getting a Call as a Mechanic," 1.30, "Pedal to the Metal," "Unusual Task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(25, "Enter Any House Except Your Own," 1, 30, "Burglar," "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(26, "Rent any transport", 1, 30, "Car sharing", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(27, "Wash the vehicle at the car wash", 1, 30, "Moidodyr", "Easy task", 666, BattlePassRewardDiff.Easy),
			new BattlePassTask(28, "Buy any firework", 1, 30, "Money down the drain", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(29, "Buy beer 24/7", 1, 30, "A bright unfiltered future...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(30, "Use paired animation", 1, 30, "Collaboration is everything," "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(31, "Play something in RP chat (/me)", 1, 30, "Roleplayer", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(32, "Shake hands with 3 people", 3, 30, "Get acquainted", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(33, "Test drive any vehicle", 1, 30, "Rate from 1 to 10", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(34, "Buy any mask in the Mask Shop", 1, 30, "Mask Wearer", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(35, "Participate in a street race", 1, 30, "It's been a while since you've been in a street race", "Hard task", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(36, "Give a Love Note via Trade", 1, 30, "Signs of Attention", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(37, "Give a Beer via Trade", 1, 30, "Share a Beer with a Neighbor!", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(38, "Visit a Hunting Store", 1, 30, "On the Outskirts", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(39, "Use Any ATM", 1, 30, "Enter Password", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(40, "Fill up the car at the gas station", 1, 30, "Full tank!", "Easy task", 350, BattlePassRewardDiff.Easy),
			new BattlePassTask(41, "Give someone a Revolver", 1, 30, "Drive a Revik", "Easy", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(42, "Fuel a vehicle from a gas can", 1, 30, "Fill up the gas", "Easy", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(43, "Buy house information from a real estate agency", 1, 30, "Experienced Hunter", "Hard", 2228, BattlePassRewardDiff.Hard),
			new BattlePassTask(44, "Buy something from LS Customs", 1, 30, "Pimp a Ride", "Hard", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(45, "Buy a Keychain at 24/7", 1, 30, "Key Picker", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(46, "Tow Any Car to the Garage", 1, 30, "Self-Tow Truck Driver", "Hard Task", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(47, "Rent a stall at the market", 1, 30, "Sold", "Hard task", 350, BattlePassRewardDiff.Hard),
			new BattlePassTask(48, "Buy something at the market", 1, 30, "Bought", "Hard task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(49, "Extend the rental of a stall at the market", 1, 30, "A real merchant!", "Hard task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(50, "Open any case", 1, 30, "Try your luck", "Hard task", 250, BattlePassRewardDiff.Hard),
			new BattlePassTask(51, "Summon Government employee with NPC help", 1, 30, "I need help!", "Hard task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(52, "Transfer pizza via trade", 1, 30, "Share pizza with a neighbor!", "Unusual task", 444, BattlePassRewardDiff.Medium),
			new BattlePassTask(53, "Make a purchase at the Barber Shop", 1, 30, "Hey, get a haircut", "Unusual task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(54, "Pass Drugs to Someone", 1, 30, "Dung", "Hard Task", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(55, "Game at the Casino", 1, 30, "F**k this Casino!", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(56, "Repeat Someone's Animation via the G-Menu", 1, 30, "Repeat", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(57, "Buy Something at the Hunting Shop", 1, 30, "Remote Shop...", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(58, "Repair 3 cars as a mechanic", 3, 30, "Senior Mechanic", "Hard Task", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(59, "Drive 15 miles with passengers as a taxi driver", 15, 30, "Senior Taxi Driver", "Hard Task", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(60, "Get PayDay", 1, 30, "Wage's dripping!", "Easy Task", 420, BattlePassRewardDiff.Easy),
			new BattlePassTask(61, "Eat some chips", 1, 30, "Yum-yum chips...", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(62, "Call a taxi 2 times", 2, 30, "TAXIIIIIIIIII!", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(63, "Ride the bus and pay the fare", 1, 30, "Pay for the fare", "Easy", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(64, "Drive 20 markers at bus driver's job", 20, 30, "Wrong turn", "Hard", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(65, "Call a mechanic", 1, 30, "Fix it!", "Easy", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(66, "Drink a beer", 1, 30, "Not 'Beer' but 'Beer'", "Easy", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(67, "Smoke Hookah 3 Times", 3, 30, "Devil's Pipe", "Hard Task", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(68, "Take 5 Puffs of a Vape", 5, 30, "Vapes Are Not Smoked, They Are Vaped", "Unusual Task", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(69, "Smoke a Bong", 1, 30, "4:20...", "Unusual Task", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(70, "Use Any Animation 3 Times", 3, 30, "Show Dancing", "Easy Task", 500, BattlePassRewardDiff.Easy),
			new BattlePassTask(71, "Vape Once", 1, 30, "Mrs. Puff...", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(72, "Trade with Another Player", 1, 30, "Functional Exchange", "Unusual Task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(73, "Put Key in Keychain", 1, 30, "Do You Have More Than Two Cars?", "Hard Task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(74, "Use Voice Radio", 1, 30, "Pshhh... Do you copy?", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(75, "Give a Rose Through Trade", 1, 30, "A Million Million Million... Scarlet Roses!", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(76, "Save Phone Number to Contacts", 1, 30, "VKontakte", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(77, "Text 3 text messages to someone who is 'online'", 3, 30, "Communication is the key to success", "Hard task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(78, "Edit an existing phone contact", 1, 30, "Hello, what's wrong?", "Hard task", 777, BattlePassRewardDiff.Hard),
			new BattlePassTask(79, "Play something in /do", 1, 30, "An outside perspective", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(80, "Whisper something (/w)", 1, 30, "I'll whisper 'Annihilator Cannon' in your ear", "Unusual Task", 250, BattlePassRewardDiff.Medium),
			new BattlePassTask(81, "Shout Something (/s)", 1, 30, "Make Some Noise", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(82, "Play Something in /try", 1, 30, "Heads/Tails", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(83, "Organize Cars in the Garage with Functional Parking", 1, 30, "Perfectionist", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(84, "Talk to NPC at the Police Station", 1, 30, "This is the police", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(85, "Talk to NPC in the hospital", 1, 30, "Medical Recommendations", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(86, "Fasten Seat Belt", 1, 30, "Ouch", "Easy", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(87, "Open Hood of Vehicle", 1, 30, "Auto Mechanic", "Easy", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(88, "Get into Trunk of Car", 1, 30, "Into the Woods", "Easy", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(89, "Point 3 Times", 3, 30, "Where?", "Easy", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(90, "Put Item in Trunk", 1, 30, "Treasure on Wheels", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(91, "Repair a Car as a Mechanic", 1, 30, "Mechanic", "Hard Task", 444, BattlePassRewardDiff.Hard),
			new BattlePassTask(92, "Deliver 10 Bags of Cash as a Cash Collector", 10, 30, "Carrying Paper Money", "Hard Task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(93, "Write an Ad on the Asphalt (/action)", 1, 30, "Advertiser 228", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(94, "Heal Yourself with First Aid Kits", 1, 30, "Catch a First Aid Kit", "Unusual Task", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(95, "Drive 10 miles as a taxi passenger", 10, 30, "Yandex.Taxi", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(96, "Get Duplicate Car Keys", 1, 30, "Change Locks", "Hard Task", 555, BattlePassRewardDiff.Hard),
			new BattlePassTask(97, "Talk to Any Quest Character", 1, 30, "Chatterbox", "Hard Task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(98, "Start treatment at the hospital on the mark", 1, 30, "Heal me completely!", "Hard task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(99, "Use an item using a quick slot", 1, 30, "In the wild west...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(100, "Win something in /todo", 1, 30, "Winner", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(101, "Show passport to someone", 1, 30, "Papers, Please", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(102, "Roll the dice in the casino (/dice)", 1, 30, "Gambling addict", "Hard task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(103, "Buy crowbar at 24/7", 1, 30, "Burglar", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(104, "Buy flashlight at 24/7", 1, 30, "In the dark of night, in the light of day...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(105, "Buy wrench at 24/7", 1, 30, "Run, dad!", "Easy task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(106, "Buy a hammer at 24/7", 1, 30, "Hammering nails", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(107, "Buy chips at 24/7", 1, 30, "Mmm chips", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(108, "Buy Pizza at 24/7", 1, 30, "I Want Pizza...", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(109, "Buy Gas Can at 24/7", 1, 30, "Every Driver's Need!", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(110, "Buy Love Note at 24/7", 1, 30, "Love Affairs", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(111, "Buy Binoculars at 24/7", 1, 30, "I'm Sitting High, Far Away" I'm looking...", "Easy Task", 2222, BattlePassRewardDiff.Easy),
			new BattlePassTask(112, "Buy a Vape 24/7", 1, 30, "Vape Nation", "Easy Task", 777, BattlePassRewardDiff.Easy),
			new BattlePassTask(113, "Buy an Umbrella 24/7", 1, 30, "What if it Rains?", "Easy Task", 555, BattlePassRewardDiff.Easy),
			new BattlePassTask(114, "Buy a Guitar 24/7", 1, 30, "Guitarist", "Easy Task", 1111, BattlePassRewardDiff.Easy),
			new BattlePassTask(115, "Buy a Camera 24/7", 1, 30, "Blogger?", "Easy Task", 1500, BattlePassRewardDiff.Easy),
			new BattlePassTask(116, "Buy a microphone at 24/7", 1, 30, "Let everyone hear!", "Easy Task", 1111, BattlePassRewardDiff.Easy),
			new BattlePassTask(117, "Buy a ball at 24/7", 1, 30, "Kicking basketball", "Easy Task", 444, BattlePassRewardDiff.Easy),
			new BattlePassTask(118, "Buy a burger at Burger-Shot", 1, 30, "Order Big Smoke", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(119, "Buy a hot dog at Burger-Shot", 1, 30, "Bun with sausage...", "Easy task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(120, "Roll 'lucky' with /try", 1, 30, "Luck is on your side", "Unusual task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(121, "Buy Sprunk at Burger-Shot", 1, 30, "Almost like Sprite...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(122, "Pass a hot dog to someone", 1, 30, "Share a sausage with ", "Unusual Task", 500, BattlePassRewardDiff.Medium),
			new BattlePassTask(123, "Give a Free Case to Someone", 1, 30, "Gifts Are Important", "Hard Task", 666, BattlePassRewardDiff.Hard),
			new BattlePassTask(124, "Open the House", 1, 30, "Expecting Guests", "Hard Task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(125, "Close the House", 1, 30, "Not Expecting Guests", "Hard Task", 333, BattlePassRewardDiff.Hard),
			new BattlePassTask(126, "Give a Token to the Driver as a Passenger", 1, 30, "Take Me There!", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(127, "Buy a sandwich at Burger-Shot", 1, 30, "Burger King", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(128, "Buy an eCola at Burger-Shot", 1, 30, "Pepsi-Cola", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(129, "Visit and explore any GunShop", 1, 30, "Local Wikipedia", "Easy Task", 250, BattlePassRewardDiff.Easy),
			new BattlePassTask(130, "Buy any weapon at the GunShop", 1, 30, "For fun", "Unusual Task", 333, BattlePassRewardDiff.Medium),
			new BattlePassTask(131, "Play Mafia", 1, 30, "Zubenko Mikhail Petrovich", "Hard Task", 500, BattlePassRewardDiff.Hard),
			new BattlePassTask(132, "Play Tank Royale", 1, 30, "Greetings to the tankers", "Unusual Task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(133, "Give someone the key to fix the car", 1, 30, "The key to my heart...", "Unusual task", 350, BattlePassRewardDiff.Medium),
			new BattlePassTask(134, "Eat pizza", 1, 30, "Mmm, Hawaiian...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(135, "Eat a sandwich", 1, 30, "Subway is taking a break!", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(136, "Drink Sprunk", 1, 30, "Refreshing...", "Easy task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(137, "Eat a Hot Dog", 1, 30, "Sausage Bun", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(138, "Drink an e-Cola", 1, 30, "Coke", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(139, "Smoke a Joint (Use Drugs)", 1, 30, "4:20", "Unusual Task", 420, BattlePassRewardDiff.Medium),
			new BattlePassTask(140, "Eat a Burger", 1, 30, "Going to the Gucci store in St. Petersburg", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(141, "Trade in an e-Cola", 1, 30, "Share a Coke!", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(142, "Trade in a Sprunk", 1, 30, "Refresh a Friend", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(143, "Trade in a Burger", 1, 30, "Delivery for a Friend", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(144, "Trade a Sandwich", 1, 30, "Share a Sandwich!", "Easy Task", 222, BattlePassRewardDiff.Easy),
			new BattlePassTask(145, "Trade a First Aid Kit", 1, 30, "Get Well, Bro", "Unusual Task", 222, BattlePassRewardDiff.Medium),
			new BattlePassTask(146, "Trade a Note", 1, 30, "Message", "Hard Task", 222, BattlePassRewardDiff.Hard),
			
        };

		public static List<BattlePassReward> BattlePassAwards = new List<BattlePassReward>
		{
			new BattlePassReward(0, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(1, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
			new BattlePassReward(3, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Rose, count: 1),
			new BattlePassReward(7, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(8, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(9, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pistol, count: 1),
			new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(12, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Umbrella, count: 1),
			new BattlePassReward(14, type: BattlePassRewardType.Item, itemId: (int)ItemId.AssaultRifleMk2, count: 1),
			new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(16, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(19, type: BattlePassRewardType.Vip, itemId: 4, count: 2),
			new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Vape, count: 1, data:"100"),
			new BattlePassReward(21, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(22, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Revolver, count: 1),
			new BattlePassReward(24, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(26, type: BattlePassRewardType.Money, count: 666),
			new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(28, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(29, type: BattlePassRewardType.Money, count: 888),
			new BattlePassReward(30, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Gusenberg, count: 1),
			new BattlePassReward(32, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(34, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework1, count: 3),
			new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe1, count: 1, data:"300"),
			new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.LoveNote, count: 1),
			new BattlePassReward(38, type: BattlePassRewardType.Money, count: 1000),
			new BattlePassReward(39, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(41, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(42, type: BattlePassRewardType.Item, itemId: (int)ItemId.Microphone, count: 1),
			new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(46, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(47, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.SMG, count: 1),
			new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(50, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Revolver, count: 1),
			new BattlePassReward(52, type: BattlePassRewardType.Item, itemId: (int)ItemId.BodyArmor, count: 3),
			new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(54, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Rose, count: 1),
			new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Musket, count: 1),
			new BattlePassReward(58, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(59, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pistol, count: 1),
			new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.WorkAxe, count: 1, data:"1250"),
			new BattlePassReward(62, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework3, count: 3),
			new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(66, type: BattlePassRewardType.Donate, count: 111),
			new BattlePassReward(67, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(68, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.AssaultShotgun, count: 1),
			new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Guitar, count: 1),
			new BattlePassReward(71, type: BattlePassRewardType.Money, count: 777),
			new BattlePassReward(72, type: BattlePassRewardType.Donate, count: 100),
			new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(73, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(75, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(76, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(78, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(79, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(81, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(83, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(84, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework2, count: 3),
			new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe2, count: 1, data:"1248"),
			new BattlePassReward(87, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(88, type: BattlePassRewardType.Money, count: 1111),
			new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(90, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.SMGMk2, count: 1),
			new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(93, type: BattlePassRewardType.Money, count: 1228),
			new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(95, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(96, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(97, type: BattlePassRewardType.Money, count: 1228),
			new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.SNSPistol, count: 1),
			new BattlePassReward(101, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(102, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.VintagePistol, count: 1),
			new BattlePassReward(104, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(107, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(108, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(109, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Drugs, count: 5),
			new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Camera, count: 1),
			new BattlePassReward(112, type: BattlePassRewardType.Vip, itemId: 4, count: 3),
			new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Bong, count: 1, data:"420"),
			new BattlePassReward(114, type: BattlePassRewardType.Donate, count: 120),
			new BattlePassReward(115, type: BattlePassRewardType.Item, itemId: (int)ItemId.Firework4, count: 3),
			new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Pickaxe3, count: 1, data: "2250"),
			new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(118, type: BattlePassRewardType.Money, count: 1337),
			new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Hookah, count: 1, data:"1000"),
			new BattlePassReward(120, type: BattlePassRewardType.Donate, count: 200),
			new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case3, count: 1),
			new BattlePassReward(123, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case4, count: 1),
			new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
			new BattlePassReward(125, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
			new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
			new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
			new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
			new BattlePassReward(128, type: BattlePassRewardType.Donate, count: 420),
			new BattlePassReward(129, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
			new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
			new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, data:"Niva", name:"Нива", count: 1),
		};

		public static List<BattlePassReward> BattlePassAwardsPremium = new List<BattlePassReward>
		{
			new BattlePassReward(0, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(1, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(2, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(3, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_0_False", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(4, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_0_False", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(5, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(6, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(7, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(8, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(9, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(10, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(11, type: BattlePassRewardType.Item, itemId: (int)ItemId.CombatMGMk2, count: 1),
            new BattlePassReward(12, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(12, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(13, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(14, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(15, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(16, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(17, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(18, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(19, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(19, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(20, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(21, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(22, type: BattlePassRewardType.Item, itemId: (int)ItemId.FlareGun, count: 1),
            new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(23, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(24, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(25, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(26, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(27, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(28, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(29, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(30, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_2_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(31, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(32, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(33, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_2_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(34, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(35, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(36, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(37, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(38, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(39, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(40, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_0_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(41, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_0_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(42, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(43, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(44, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(45, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(46, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_3_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(46, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_3_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(47, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavySniperMk2, count: 1),
            new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(48, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_3_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(49, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_3_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(50, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(51, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(52, type: BattlePassRewardType.Money, count: 5000),
            new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_1_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(53, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_1_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(54, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(55, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(56, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(57, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_4_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(58, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_4_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(59, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(60, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(61, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(62, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_5_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(62, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_5_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(63, type: BattlePassRewardType.Item, itemId: (int)ItemId.HeavyShotgun, count: 1),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_0_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(64, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_0_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(65, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_4_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(66, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_4_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(67, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(68, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(69, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_6_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(70, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_6_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(71, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(71, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(72, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(73, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(74, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(75, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(76, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(77, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(78, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(79, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_7_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(80, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_7_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(81, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(82, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(83, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(84, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case5, count: 1),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_1_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(85, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_1_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_5_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(86, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_5_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(87, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "462_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(88, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "485_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(89, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_8_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(90, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_8_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(91, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(92, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(93, type: BattlePassRewardType.Donate, count: 228),
            new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "468_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(94, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "483_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "166_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(95, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "175_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(96, type: BattlePassRewardType.Vip, itemId: 4, count: 10),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(97, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(98, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(99, type: BattlePassRewardType.Item, itemId: (int)ItemId.RevolverMk2, count: 1),
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_9_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(100, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "209_9_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(101, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case12, count: 1),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "465_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(102, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "479_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(103, type: BattlePassRewardType.Item, itemId: (int)ItemId.MarksmanRifle, count: 1),
            new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "163_2_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(104, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "173_2_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(105, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "464_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(106, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "481_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(107, type: BattlePassRewardType.Donate, count: 250),
            new BattlePassReward(108, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case6, count: 1),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "469_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(109, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "484_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "164_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(110, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "176_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(111, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_4_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(112, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_4_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(113, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_4_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(114, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_4_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(115, type: BattlePassRewardType.Vip, itemId: 4, count: 7),
            new BattlePassReward(116, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
            new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "463_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(117, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "480_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(118, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "165_5_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(119, type: BattlePassRewardType.Item, itemId: (int)ItemId.Leg, count: 1, data: "174_5_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(120, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "467_5_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(121, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "482_5_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_6_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(122, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_6_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(123, type: BattlePassRewardType.Donate, count: 333),
            new BattlePassReward(124, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case7, count: 1),
            new BattlePassReward(125, type: BattlePassRewardType.Vip, itemId: 4, count: 10),
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_2_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(126, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "210_2_True", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "466_3_True", gender: BattlePassRewardGender.Man),
            new BattlePassReward(127, type: BattlePassRewardType.Item, itemId: (int)ItemId.Top, count: 1, data: "486_3_False", gender: BattlePassRewardGender.Woman),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case8, count: 1,gender: BattlePassRewardGender.Man),
            new BattlePassReward(128, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case9, count: 1,gender: BattlePassRewardGender.Woman),
            new BattlePassReward(129, type: BattlePassRewardType.Item, itemId: (int)ItemId.Case11, count: 1),
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_7_True", gender: BattlePassRewardGender.Man), 
            new BattlePassReward(130, type: BattlePassRewardType.Item, itemId: (int)ItemId.Mask, count: 1, data: "212_7_True", gender: BattlePassRewardGender.Woman), 
            new BattlePassReward(131, type: BattlePassRewardType.Item, itemId: (int)ItemId.CarCoupon, count: 1, data: "lc100", name:"Land Cruiser 100"),
		};

    }
}